version: '3'
services:
  # 1. Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.2.3
    container_name: es-node01
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # 2. Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 # 注意：这里用服务名连接
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  # Logstash 已移除，Filebeat 直连 ES

  # 3. Filebeat (新增)
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.19.9
    container_name: filebeat
    user: root # 使用 root 权限，防止读取不到日志文件
    volumes:
      # A. 挂载配置文件: 把当前目录的 filebeat.yml 映射进去
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro

      # B. 挂载日志目录: 把 Windows 的 logs 目录 映射到 容器内的 /var/log/app_logs
      - ./logs:/var/log/app_logs:ro

    # 禁用权限检查 (解决 Windows 挂载配置文件权限报错的问题)
    command: ["filebeat", "-e", "--strict.perms=false"]

    depends_on:
      - elasticsearch

  # 4. MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=usergrowth
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  # 5. Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass 123456

  # 6. Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686" # Web UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  es_data:
  mysql_data:
  redis_data: