app:
  name: "usergrowth"
  port: 8080
  logPath: "./logs"

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  pass: "123456"
  db: "usergrowth"

redis:
  host: "localhost"
  port: 6379
  pass: "123456"

elasticsearch:
  host: "localhost"
  port: 9200
  maxQueueSize: 100
  workers: 3
  logIndex: "usergrowth-*"
  maxBatchSize: 2

jwt:
  secret: "test"
  expire: 1500s

middleware:
  error: true
  access: true
  jwt: true

tracing:
  endpoint: "localhost:4318"
  path: "/v1/traces"
  serviceName: "gf-growth"