app:
  name: "usergrowth"
  port: 8080
  logPath: "./logs"

mysql:
  host: "localhost"
  port: 3306
  user: "root"
  pass: 123456
  db: "usergrowth"

redis:
  host: "localhost"
  port: 6379
  user: "root"
  pass: 123456

elasticsearch:
  host: "localhost"
  port: 9200
  maxQueueSize: 100
  workers: 3
  logIndex: "usergrowth-*"
  maxBatchSize: 2

jwt:
  secret: "test"
  expire: 150s